# config1.yml
location: '上海'
snowboy:
  hotword: 'snowboy/resources/wukong_tc.pmdl'
  sensitivity: 0.38

Weather:
  enable: true

server:
  port: '5000'
  name: 'tchang'
  password: '12345689'

# 讯飞语音服务
# appid 及 api_key 需前往
# https://xfyun.cn/
# 注册创建是WebAPI应用，并赋予流式语音听写及在线语音合成两项能力
xunfei_yuyin:
    appid: '5d7e11a8'
    api_key: '96ff7d1e79f6f780aa1a14cc7ce54547'  # 语音听写
    api_secret: 'fefd2cecbef56f96ab87d4d2a0ff472c'
    voice: 'xiaoyan'  # 全部可选：https://console.xfyun.cn/services/tts
# 语音合成服务配置
# 可选值：
# han-tts       - HanTTS
# baidu-tts     - 百度语音合成（推荐）
# xunfei-tts    - 讯飞语音合成
# ali-tts       - 阿里语音合成（推荐）
# tencent-tts   - 腾讯云语音合成（推荐）
tts_engine: xunfei-tts

# 语音识别服务配置
# 可选值：
# baidu-asr     - 百度在线语音识别
# xunfei-asr    - 讯飞语音识别
# ali-asr       - 阿里语音识别
# tencent-asr   - 腾讯云语音识别（推荐）
asr_engine: xunfei-asr

